telegram_bot_token: 8700819180:AAEmR5VSYgVbm9czE9VxCw0Vnt2GmWsknzo
server:
  server_id: home_server_01
  server_name: Home PC
security:
  allowed_telegram_user_ids:
  - 820565883
paths:
  base_storage_path: E:/Media
  incoming_temp_path: E:/Media/_incoming_temp
  database_path: data/media_sorter.db
behavior:
  delete_telegram_message_after_save: true
  duplicate_action: skip
  allow_new_folder: true
  keep_original_filename: true
categories:
- name: RR
  folders:
  - name: School
  - name: Home
- name: Product Pics
  folders:
  - name: PM Hoist
    folders:
    - name: '2026'
    - name: Control Panel
    - name: Machine Photos
  - name: Monkey Hoist
    folders:
    - name: '2026'
    - name: Machine Photos
- name: Site Pics
  folders:
  - name: PM Hoist
    folders:
    - name: '2026'
    - name: Customer Sites
  - name: Concrete Mixer
    folders:
    - name: '2026'
    - name: Customer Sites
logging:
  level: INFO
  file: logs/media_sorter.log
webui:
  host: 127.0.0.1
  port: 8080
